export enum queryKeys {
  // category
  FETCH_CATEGORIES = "FETCH_CATEGORIES",

  // POSTS
  FETCH_POSTS_COMBINED = "FETCH_POSTS_COMBINED",
  FETCH_POSTS_BY_QUERY = "FETCH_POSTS_BY_QUERY",
  GET_SINGLE_POST = "GET_SINGLE_POST",
}
